/* Autogenerated header */
#pragma once

namespace/*or class/struct?*/ `anonymous namespace'
{
  // Nested containers:
  class PollingThreadExec
  {
  public:
  };

  class StatisticsProcessor : public PollingThread
  {
    // VFTable. Offset=0, Size=11, Start=11
    // Corresponding base: thread::thread::PollingThread
    // Owner: SophisSystem.dll
    // VFTable with 0 offset end

  public:
  };


};
