/* Autogenerated header */
#pragma once

namespace/*or class/struct?*/ CSRAPIConfiguration
{
  // Nested containers:
  class/*or struct*/ DataIntegrity
  {
    // Static functions:
    public: static bool EnableDataIntegrity(void)
  public:
  };


};
