/* Autogenerated header */
#pragma once

class/*or struct*/ CSRCurrencyCreatorImpl : public ICSRCurrencyCreator
{
  // Functions:
  public: CSRCurrencyCreatorImpl(void)
#if 0 // All found virtual functions names:
  public: virtual ~CSRCurrencyCreatorImpl(void)
  public: virtual class sophis::static_data::CSRCurrency const * CreateFromDescription(class sophis::tools::dataModel::DataSet const &)
  private: virtual struct sophis::DAL::CurrencyDescription const GetCurrencyDescription(class sophis::tools::dataModel::DataSet const &)
  public: virtual long const UpdateBankHolidaysFromDescription(class sophis::tools::dataModel::DataSet const &)
#endif

  // VFTable. Offset=0, Size=4, Start=0
  // Corresponding base: static_data::static_data::ICSRCurrencyCreator
  // Owner: SophisXmlTools.dll
  // Added virtual functions:
  public: virtual ~CSRCurrencyCreatorImpl(void); // 0
  public: virtual class sophis::static_data::CSRCurrency const * CreateFromDescription(class sophis::tools::dataModel::DataSet const &); // 1
  public: virtual long const UpdateBankHolidaysFromDescription(class sophis::tools::dataModel::DataSet const &); // 2
  private: virtual struct sophis::DAL::CurrencyDescription const GetCurrencyDescription(class sophis::tools::dataModel::DataSet const &); // 3
  // VFTable with 0 offset end

public:
};
