/* Autogenerated header */
#pragma once

class CSRic
{
  // Functions:
  public: void GetDescription(class sophis::tools::dataModel::DataSet &) const
  public: int Save(void *)
  public: void UpdateFromDescription(class sophis::tools::dataModel::DataSet const &)
  // Static functions:
  public: static class CSRic * GetCSRic(long)
public:
};
