/* Autogenerated header */
#pragma once

class/*or struct*/ CSRPreference
{
  // Static functions:
  public: static void GetNthTable(int, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>> &)
  public: static bool IsSimulationMode(void)
public:
};
