/* Autogenerated header */
#pragma once

class/*or struct*/ CSRPlaceCreatorImpl
{
  // Static functions:
  public: static struct sophis::DAL::PlaceDescription * GetPlaceDescriptionFromDataSet(class sophis::tools::dataModel::DataSet const &)
  public: static void SendPlaceCreateEvent(struct sophis::DAL::PlaceDescription *)
  public: static struct sophis::DAL::PlaceDescription * SynchronizePlaceInstance(struct sophis::DAL::PlaceDescription *, class sophis::tools::CSREventVector &, bool)
  public: static void UpdatePlacesWithHolidays(struct sophis::DAL::PlaceDescription *, class sophis::tools::CSREventVector &)
public:
};
