/* Autogenerated header */
#pragma once

class CSRSiteManager
{
  // Functions:
  public: double GetCurrentSiteCutoffInDBTimeZone(void)
  // Static functions:
  public: static class CSRSiteManager & GetInstance(void)
public:
};
