/* Autogenerated header */
#pragma once

class/*or struct*/ CSXMLDocument
{
  // Functions:
  public: CSXMLDocument(void)
  public: bool CopyFromProduit(struct sophis::DAL::OptionInstrumentData **)
  public: long FindIdentifiers(class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>> const *)
  public: class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>> const * GetBuffer(void) const
#if 0 // All found virtual functions names:
  public: virtual ~CSXMLDocument(void)
#endif

public:
};
