/* Autogenerated header */
#pragma once

class/*or struct*/ type_info
{
  // VFTable. Offset=0, Size=1, Start=0
  // Owner: SophisSystem.dll
  // Added virtual functions:
  public: virtual void unknown_vf_0_0(void); // 0
  // VFTable with 0 offset end

public:
};
